vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1

require("roops.plugins-setup")
require("roops.core.options")
require("roops.core.keymaps")
require("roops.core.colorscheme")
require("roops.plugins.comment")
require("roops.plugins.nvim-tree")
require("roops.plugins.lualine")
require("roops.plugins.telescope")
require("roops.plugins.nvim-cmp")
require("roops.plugins.lsp.mason")
require("roops.plugins.lsp.lspsaga")
require("roops.plugins.lsp.lspconfig")
require("roops.plugins.lsp.null-ls")
require("roops.plugins.autopairs")
require("roops.plugins.treesitter")
require("roops.plugins.gitsigns")
require("roops.plugins.rust-tools")
require("roops.plugins.inlay-hints")
require("roops.plugins.wilder")
require("roops.plugins.indent-blankline")
require("roops.plugins.toggleterm")
require("roops.plugins.which-key")
require("roops.plugins.treesitter-context")
require("roops.plugins.leap")
require("roops.plugins.auto-session")
require("roops.plugins.session-lens")
require("roops.plugins.bufferline")
require("roops.plugins.tailwind-sorter")
